//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliExtract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiliExtract.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application data folders.
        /// </summary>
        public static string AboutPage_ApplicationDataFolders {
            get {
                return ResourceManager.GetString("AboutPage_ApplicationDataFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string AboutPage_BuildTextBlock_Text {
            get {
                return ResourceManager.GetString("AboutPage_BuildTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string AboutPage_DataFolder {
            get {
                return ResourceManager.GetString("AboutPage_DataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project links.
        /// </summary>
        public static string AboutPage_ProjectLinks {
            get {
                return ResourceManager.GetString("AboutPage_ProjectLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project website on GitHub.
        /// </summary>
        public static string AboutPage_ProjectWebsiteOnGitHub {
            get {
                return ResourceManager.GetString("AboutPage_ProjectWebsiteOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string AboutPage_TempFolder {
            get {
                return ResourceManager.GetString("AboutPage_TempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party libraries.
        /// </summary>
        public static string AboutPage_ThirdPartyLibraries {
            get {
                return ResourceManager.GetString("AboutPage_ThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB server IPv4 address &amp; port..
        /// </summary>
        public static string AdbSettingsWindow_AdbServerAddress_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AdbServerAddress_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB server address.
        /// </summary>
        public static string AdbSettingsWindow_AdbServerAddress_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AdbServerAddress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ADB server automatically if it hasn&apos;t been started..
        /// </summary>
        public static string AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic start ADB server.
        /// </summary>
        public static string AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followings are advanced ADB settings.
        ///Changing them may lead to unexpected errors.
        ///If you are not familiar with these options, DO NOT change..
        /// </summary>
        public static string AdbSettingsWindow_Description {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string AdbSettingsWindow_Ip {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill ADB server when BiliExtract exits..
        /// </summary>
        public static string AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill ADB server on exit.
        /// </summary>
        public static string AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string AdbSettingsWindow_Port {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ADB server when BiliExtract starts..
        /// </summary>
        public static string AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ADB server on startup.
        /// </summary>
        public static string AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB Settings.
        /// </summary>
        public static string AdbSettingsWindow_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default IP address for connecting wireless devices.
        ///Used by `adb pair` &amp; `adb connect` command..
        /// </summary>
        public static string AdbSettingsWindow_WirelessDeviceDefaultIp_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_WirelessDeviceDefaultIp_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless device default IP.
        /// </summary>
        public static string AdbSettingsWindow_WirelessDeviceDefaultIp_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_WirelessDeviceDefaultIp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiliExtract.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_About {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_Dashboard {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_Log {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_Settings {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the accent color of BiliExtract..
        /// </summary>
        public static string SettingsPage_AccentColor_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_AccentColor_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string SettingsPage_AccentColor_Title {
            get {
                return ResourceManager.GetString("SettingsPage_AccentColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default ADB behavior, server host, etc..
        /// </summary>
        public static string SettingsPage_AdvancedAdbSettingsCardAction_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedAdbSettingsCardAction_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced ADB settings.
        /// </summary>
        public static string SettingsPage_AdvancedAdbSettingsCardAction_Title {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedAdbSettingsCardAction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set external ADB (adb.exe) absolute path..
        /// </summary>
        public static string SettingsPage_ExternalAdbPathTextBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalAdbPathTextBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External ADB path.
        /// </summary>
        public static string SettingsPage_ExternalAdbPathTextBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalAdbPathTextBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set external FFmpeg (ffmpeg.exe) absolute path..
        /// </summary>
        public static string SettingsPage_ExternalFFmpegPathTextBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalFFmpegPathTextBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External FFmpeg path.
        /// </summary>
        public static string SettingsPage_ExternalFFmpegPathTextBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalFFmpegPathTextBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set BiliExtract Theme (Light, Dark, Follow System)..
        /// </summary>
        public static string SettingsPage_ThemeComboBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeComboBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsPage_ThemeComboBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeComboBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BiliExtract built-in ADB for Android related features..
        /// </summary>
        public static string SettingsPage_UseBuiltInAdbToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInAdbToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in ADB.
        /// </summary>
        public static string SettingsPage_UseBuiltInAdbToggleSwitch_Title {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInAdbToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BiliExtract built-in FFmpeg for video / audio encode &amp; decode..
        /// </summary>
        public static string SettingsPage_UseBuiltInFFmpegToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInFFmpegToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in FFmpeg.
        /// </summary>
        public static string SettingsPage_UseBuiltInFFmpegToggleSwitch_Title {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInFFmpegToggleSwitch_Title", resourceCulture);
            }
        }
    }
}
