//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliExtract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiliExtract.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application data folders.
        /// </summary>
        public static string AboutPage_ApplicationDataFolders {
            get {
                return ResourceManager.GetString("AboutPage_ApplicationDataFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string AboutPage_BuildTextBlock_Text {
            get {
                return ResourceManager.GetString("AboutPage_BuildTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string AboutPage_DataFolder {
            get {
                return ResourceManager.GetString("AboutPage_DataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project links.
        /// </summary>
        public static string AboutPage_ProjectLinks {
            get {
                return ResourceManager.GetString("AboutPage_ProjectLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project website on GitHub.
        /// </summary>
        public static string AboutPage_ProjectWebsiteOnGitHub {
            get {
                return ResourceManager.GetString("AboutPage_ProjectWebsiteOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string AboutPage_TempFolder {
            get {
                return ResourceManager.GetString("AboutPage_TempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party executables.
        /// </summary>
        public static string AboutPage_ThirdPartyExecutables {
            get {
                return ResourceManager.GetString("AboutPage_ThirdPartyExecutables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party libraries.
        /// </summary>
        public static string AboutPage_ThirdPartyLibraries {
            get {
                return ResourceManager.GetString("AboutPage_ThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB server IPv4 address &amp; port..
        /// </summary>
        public static string AdbSettingsWindow_AdbServerAddress_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AdbServerAddress_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB server address.
        /// </summary>
        public static string AdbSettingsWindow_AdbServerAddress_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AdbServerAddress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ADB server automatically if it hasn&apos;t been started..
        /// </summary>
        public static string AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic start ADB server.
        /// </summary>
        public static string AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_AutomaticStartAdbServerToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followings are advanced ADB settings.
        ///Changing them may lead to unexpected errors.
        ///If you are not familiar with these options, DO NOT change..
        /// </summary>
        public static string AdbSettingsWindow_Description {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string AdbSettingsWindow_Ip {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill ADB server when BiliExtract exits..
        /// </summary>
        public static string AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill ADB server on exit.
        /// </summary>
        public static string AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_KillAdbServerOnExitToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string AdbSettingsWindow_Port {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ADB server when BiliExtract starts..
        /// </summary>
        public static string AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ADB server on startup.
        /// </summary>
        public static string AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_StartAdbServerOnStartupToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB Settings.
        /// </summary>
        public static string AdbSettingsWindow_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default IP address for connecting wireless devices.
        ///Used by `adb pair` &amp; `adb connect` command..
        /// </summary>
        public static string AdbSettingsWindow_WirelessDeviceDefaultIp_Subtitle {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_WirelessDeviceDefaultIp_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless device default IP.
        /// </summary>
        public static string AdbSettingsWindow_WirelessDeviceDefaultIp_Title {
            get {
                return ResourceManager.GetString("AdbSettingsWindow_WirelessDeviceDefaultIp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiliExtract.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log count: {0}.
        /// </summary>
        public static string LogPage_LogCountTextBlock_Text {
            get {
                return ResourceManager.GetString("LogPage_LogCountTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min log level: {0}.
        /// </summary>
        public static string LogPage_LogMinLevelTextBlock_Text {
            get {
                return ResourceManager.GetString("LogPage_LogMinLevelTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogPage_Title {
            get {
                return ResourceManager.GetString("LogPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set debug log level style..
        /// </summary>
        public static string LogPageStyleSettingsWindow_DebugLogLevelStyle_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_DebugLogLevelStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug log level style.
        /// </summary>
        public static string LogPageStyleSettingsWindow_DebugLogLevelStyle_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_DebugLogLevelStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set error log level style..
        /// </summary>
        public static string LogPageStyleSettingsWindow_ErrorLogLevelStyle_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_ErrorLogLevelStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log level style.
        /// </summary>
        public static string LogPageStyleSettingsWindow_ErrorLogLevelStyle_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_ErrorLogLevelStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set exception style..
        /// </summary>
        public static string LogPageStyleSettingsWindow_ExceptionStyle_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_ExceptionStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception style.
        /// </summary>
        public static string LogPageStyleSettingsWindow_ExceptionStyle_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_ExceptionStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set filename color..
        /// </summary>
        public static string LogPageStyleSettingsWindow_FilenameColorColorPicker_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_FilenameColorColorPicker_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename color.
        /// </summary>
        public static string LogPageStyleSettingsWindow_FilenameColorColorPicker_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_FilenameColorColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text font family..
        /// </summary>
        public static string LogPageStyleSettingsWindow_FontComboBox_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_FontComboBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string LogPageStyleSettingsWindow_FontComboBox_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_FontComboBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set info log level style..
        /// </summary>
        public static string LogPageStyleSettingsWindow_InfoLogLevelStyle_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_InfoLogLevelStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info log level style.
        /// </summary>
        public static string LogPageStyleSettingsWindow_InfoLogLevelStyle_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_InfoLogLevelStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set number color..
        /// </summary>
        public static string LogPageStyleSettingsWindow_NumberColorColorPicker_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_NumberColorColorPicker_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number color.
        /// </summary>
        public static string LogPageStyleSettingsWindow_NumberColorColorPicker_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_NumberColorColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset current customize settings to default..
        /// </summary>
        public static string LogPageStyleSettingsWindow_ResetToDefaultButton_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_ResetToDefaultButton_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        public static string LogPageStyleSettingsWindow_ResetToDefaultButton_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_ResetToDefaultButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set string color..
        /// </summary>
        public static string LogPageStyleSettingsWindow_StringColorColorPicker_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_StringColorColorPicker_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String color.
        /// </summary>
        public static string LogPageStyleSettingsWindow_StringColorColorPicker_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_StringColorColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application theme to customize..
        /// </summary>
        public static string LogPageStyleSettingsWindow_TargetThemeComboBox_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TargetThemeComboBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target theme.
        /// </summary>
        public static string LogPageStyleSettingsWindow_TargetThemeComboBox_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TargetThemeComboBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set basic text color..
        /// </summary>
        public static string LogPageStyleSettingsWindow_TextColorColorPicker_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TextColorColorPicker_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string LogPageStyleSettingsWindow_TextColorColorPicker_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TextColorColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set time color for hour, minute and second..
        /// </summary>
        public static string LogPageStyleSettingsWindow_TimeColorHMSColorPicker_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TimeColorHMSColorPicker_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time color (H:M:S).
        /// </summary>
        public static string LogPageStyleSettingsWindow_TimeColorHMSColorPicker_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TimeColorHMSColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set time color for year, month and day..
        /// </summary>
        public static string LogPageStyleSettingsWindow_TimeColorYMDColorPicker_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TimeColorYMDColorPicker_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time color (Y/M/D).
        /// </summary>
        public static string LogPageStyleSettingsWindow_TimeColorYMDColorPicker_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_TimeColorYMDColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Page Customize.
        /// </summary>
        public static string LogPageStyleSettingsWindow_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set warning log level style..
        /// </summary>
        public static string LogPageStyleSettingsWindow_WarningLogLevelStyle_Subtitle {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_WarningLogLevelStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning log level style.
        /// </summary>
        public static string LogPageStyleSettingsWindow_WarningLogLevelStyle_Title {
            get {
                return ResourceManager.GetString("LogPageStyleSettingsWindow_WarningLogLevelStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_About {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_Dashboard {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_Log {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_NavigationStore_Item_Settings {
            get {
                return ResourceManager.GetString("MainWindow_NavigationStore_Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All file (*.*).
        /// </summary>
        public static string SaveFileDialog_Filter_AllFile {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filter_AllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file (*.log).
        /// </summary>
        public static string SaveFileDialog_Filter_LogFile {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filter_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file (*.txt).
        /// </summary>
        public static string SaveFileDialog_Filter_TextFile {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filter_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log file to.
        /// </summary>
        public static string SaveFileDialog_SaveLog_Title {
            get {
                return ResourceManager.GetString("SaveFileDialog_SaveLog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the accent color of BiliExtract..
        /// </summary>
        public static string SettingsPage_AccentColor_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_AccentColor_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string SettingsPage_AccentColor_Title {
            get {
                return ResourceManager.GetString("SettingsPage_AccentColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default ADB behavior, server host, etc..
        /// </summary>
        public static string SettingsPage_AdvancedAdbSettingsCardAction_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedAdbSettingsCardAction_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced ADB settings.
        /// </summary>
        public static string SettingsPage_AdvancedAdbSettingsCardAction_Title {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedAdbSettingsCardAction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file BiliExtract currently is writing to..
        /// </summary>
        public static string SettingsPage_CurrentLogFileCardControl_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_CurrentLogFileCardControl_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current log file.
        /// </summary>
        public static string SettingsPage_CurrentLogFileCardControl_Title {
            get {
                return ResourceManager.GetString("SettingsPage_CurrentLogFileCardControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set external ADB (adb.exe) absolute path..
        /// </summary>
        public static string SettingsPage_ExternalAdbPathTextBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalAdbPathTextBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External ADB path.
        /// </summary>
        public static string SettingsPage_ExternalAdbPathTextBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalAdbPathTextBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set external FFmpeg (ffmpeg.exe) absolute path..
        /// </summary>
        public static string SettingsPage_ExternalFFmpegPathTextBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalFFmpegPathTextBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External FFmpeg path.
        /// </summary>
        public static string SettingsPage_ExternalFFmpegPathTextBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_ExternalFFmpegPathTextBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum log level BiliExtract will record..
        /// </summary>
        public static string SettingsPage_MinLogLevelComboBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_MinLogLevelComboBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min log level.
        /// </summary>
        public static string SettingsPage_MinLogLevelComboBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_MinLogLevelComboBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string SettingsPage_RichLogViewStyle_Button_Content {
            get {
                return ResourceManager.GetString("SettingsPage_RichLogViewStyle_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set rich text style of log messages in log page..
        /// </summary>
        public static string SettingsPage_RichLogViewStyle_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_RichLogViewStyle_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log page style.
        /// </summary>
        public static string SettingsPage_RichLogViewStyle_Title {
            get {
                return ResourceManager.GetString("SettingsPage_RichLogViewStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set BiliExtract Theme (Light, Dark, Follow System)..
        /// </summary>
        public static string SettingsPage_ThemeComboBox_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeComboBox_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsPage_ThemeComboBox_Title {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeComboBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BiliExtract built-in ADB for Android related features..
        /// </summary>
        public static string SettingsPage_UseBuiltInAdbToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInAdbToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in ADB.
        /// </summary>
        public static string SettingsPage_UseBuiltInAdbToggleSwitch_Title {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInAdbToggleSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BiliExtract built-in FFmpeg for video / audio encode &amp; decode..
        /// </summary>
        public static string SettingsPage_UseBuiltInFFmpegToggleSwitch_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInFFmpegToggleSwitch_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in FFmpeg.
        /// </summary>
        public static string SettingsPage_UseBuiltInFFmpegToggleSwitch_Title {
            get {
                return ResourceManager.GetString("SettingsPage_UseBuiltInFFmpegToggleSwitch_Title", resourceCulture);
            }
        }
    }
}
