name: Update Platform-Tools

on:
  workflow_dispatch:

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update platform-tools
        run: |
          wget -O platform-tools.zip  https://dl.google.com/android/repository/platform-tools-latest-windows.zip 
          unzip -o platform-tools.zip
          rm platform-tools.zip
        working-directory: ${{github.workspace}}/BiliExtract.Lib/Binary

      - name: Extract Branch Name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Push Files
        uses: actions-js/push@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          author_email: ${{secrets.BOT_EMAIL}}
          author_name: ${{secrets.BOT_USERNAME}}
          message: update platform-tools
          branch: ${{steps.extract_branch.outputs.branch}}