name: Update FFmpeg

on:
  workflow_dispatch:

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update platform-tools
        run: |
          wget -O ffmpeg-essentials.7z https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z
          7z x ffmpeg-essentials.7z -offmpeg_temp -y
          mv ffmpeg_temp/ffmpeg*/bin/ffmpeg.exe ffmpeg/ffmpeg.exe
          rm -rf ffmpeg-essentials.7z ffmpeg_temp
        working-directory: ${{github.workspace}}/BiliExtract.Lib/Binary

      - name: Extract Branch Name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Push Files
        uses: actions-js/push@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          author_email: ${{secrets.BOT_EMAIL}}
          author_name: ${{secrets.BOT_USERNAME}}
          message: update ffmpeg
          branch: ${{steps.extract_branch.outputs.branch}}
